### ISSUE TITLE
Response middleware

### ISSUE THREAD

**Issue by Agrosis** [plasmaconduit/plasmaconduit-framework#32]
So, right now we have request middleware, which let us preprocess requests before controllers handle them. I think response middleware would also be a good idea, so we can postprocess responses without duplicating a lot of code.

Use cases:
* Tagging along some kind of token to return
* Logging all the responses we're returning
* Adding some headers: `_.withHeader(GenericResponseHeader("Access-Control-Allow-Origin", "*"))` (we could technically do this with nginx, but it still poses a good usecase)

@JosephMoniz

**Comment by JosephMoniz** [comment]
We don't really have the notion of request vs response middleware at all. Currently any middleware can handle pre and post processing. Session handling middleware is an example of middleware that does post (response) processing as it has to take the session, sign it and add it to the response.
